site_name: "SRE Docs Demo"
nav:
  - Главная: index.md
  - Runbooks:
      - Рост 5xx: runbooks/http_5xx_rate_high.md
      - Здоровье сервиса: runbooks/service_healthcheck_failed.md
      - Демонстрация PodInfo: runbooks/podinfo_http_errors.md
